INSERT INTO kaufmlu1.roles (id,name) VALUES (1,'administrator');
INSERT INTO kaufmlu1.roles (id,name) VALUES (2,'teacher');
INSERT INTO kaufmlu1.roles (id,name) VALUES (3,'student');
INSERT INTO kaufmlu1.roles (id,name) VALUES (4,'new user');

INSERT INTO kaufmlu1.users (id, fname, lname, email, uname, pass, dob, role) VALUES (1, 'Lukáš', 'Kaufmann', null, 'admin1', '$2y$10$qqcwN707A1.Y7YNGVmUKqulzwLjPrd7dPO6z6jOXfQOqkxlFXCwEy', '2001-07-09', 1);
INSERT INTO kaufmlu1.users (id, fname, lname, email, uname, pass, dob, role) VALUES (2, 'Testovaci', 'Ucitel', null, 'TestTeacher', '$2y$10$rEF3mkKYa6WYSzkbmV6cXufIIlbLsS3H/GnMLXruSqF1fsy5Gwl2G', '1980-10-10', 2);
INSERT INTO kaufmlu1.users (id, fname, lname, email, uname, pass, dob, role) VALUES (3, 'Testovaci', 'Student', null, 'TestStudent', '$2y$10$kDR1URvCYC6UcBx8nYUrIezuiMp7j23kQa0jAp.unIHV69aHkmn4S', '2005-10-10', 3);
INSERT INTO kaufmlu1.users (id, fname, lname, email, uname, pass, dob, role) VALUES (4, 'Testovaci', 'Ucitel 2', 'email@testmail.cz', 'TestTeacher2', '$2y$10$kHn7E/60F6CyR/URqdiVBu4laKQhzaQJOoDvgqBrZqO3RRoMIGOWi', '1976-05-04', 2);
INSERT INTO kaufmlu1.users (id, fname, lname, email, uname, pass, dob, role) VALUES (5, 'Testovaci', 'Ucitel 3', null, 'TestTeacher3', '$2y$10$z8OV8DpUWPPpazPqkUoV1OjeMgBea5Q0CMdlN5XjGjkhqReYPMs0G', '1990-11-25', 2);
INSERT INTO kaufmlu1.users (id, fname, lname, email, uname, pass, dob, role) VALUES (6, 'Testovaci', 'Ucitel 4', null, 'TestTeacher4', '$2y$10$DbyrtPO6/Asojv7IwicZYuBYu0DP.xejMffuca7hAHnzNja2yx6Mi', '1987-11-30', 2);
INSERT INTO kaufmlu1.users (id, fname, lname, email, uname, pass, dob, role) VALUES (7, 'Pavel', 'Student', null, 'TestStudent2', '$2y$10$EperddCQGRZATTuY2JDpAe4L7Qss/2eBU01Gig4s7svb6TPGZK4Ae', '2000-11-30', 3);
INSERT INTO kaufmlu1.users (id, fname, lname, email, uname, pass, dob, role) VALUES (8, 'Martin', 'Student', null, 'TestStudent3', '$2y$10$OIUxnD95gr6YieklItXk2.or4lNH2Z7kB2hG.wYl5kKFNCES45bAa', '2001-04-11', 3);
INSERT INTO kaufmlu1.users (id, fname, lname, email, uname, pass, dob, role) VALUES (9, 'Zdenek', 'Student', null, 'TestStudent4', '$2y$10$BW2bCk2BBiH4HDNoprAFs.MCnZkiEx4QaRJpkP15Mqs56hZo/sqb2', '1999-06-05', 3);
INSERT INTO kaufmlu1.users (id, fname, lname, email, uname, pass, dob, role) VALUES (10, 'Adam', 'Student', null, 'TestStudent5', '$2y$10$kTqjddLsG61bdOIrVpiDM.3BevOazG.rJaDdlKkzzbmNi1ZgFxM2S', '2004-11-11', 3);

INSERT INTO kaufmlu1.subjects (name, code) VALUES ('Webové aplikace','B01-WA');
INSERT INTO kaufmlu1.subjects (name, code) VALUES ('Počítačové sítě','B01-PS');
INSERT INTO kaufmlu1.subjects (name, code) VALUES ('Programování v C','B01-PC');
INSERT INTO kaufmlu1.subjects (name, code) VALUES ('Antická literatura','A02-AL');
INSERT INTO kaufmlu1.subjects (name, code) VALUES ('Právo','A02-PR');
INSERT INTO kaufmlu1.subjects (name, code) VALUES ('IT Právo','A02-PIT');
INSERT INTO kaufmlu1.subjects (name, code) VALUES ('Databáse','B01-DB');
INSERT INTO kaufmlu1.subjects (name, code) VALUES ('Programování v Java','B01-PJ');
INSERT INTO kaufmlu1.subjects (name, code) VALUES ('Projekt Programování','B02-PP');
INSERT INTO kaufmlu1.subjects (name, code) VALUES ('Umělá inteligence','B02-AI');
INSERT INTO kaufmlu1.subjects (name, code) VALUES ('Návrh uživatelského prostředí','B02-UX');
INSERT INTO kaufmlu1.subjects (name, code) VALUES ('Telekomunikace','B02-TK');
INSERT INTO kaufmlu1.subjects (name, code) VALUES ('Taktické plánování','A02-TP');

UPDATE kaufmlu1.subjectdetails SET anotation = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum. Nunc dapibus tortor vel mi dapibus sollicitudin. Integer vulputate sem a', description = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum. Nunc dapibus tortor vel mi dapibus sollicitudin. Integer vulputate sem a nibh rutrum consequat. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Sed convallis magna eu sem. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Nullam sit amet magna in magna gravida vehicula. Nulla', length = 16, lectures = 2, practicals = 8, labs = 0 WHERE id = 1;
UPDATE kaufmlu1.subjectdetails SET anotation = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum. Nunc dapibus tortor vel mi dapibus sollicitudin. Integer vulputate sem a', description = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum. Nunc dapibus tortor vel mi dapibus sollicitudin. Integer vulputate sem a nibh rutrum consequat. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Sed convallis magna eu sem. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Nullam sit amet magna in magna gravida vehicula. Nulla', length = 8, lectures = 2, practicals = 6, labs = 6 WHERE id = 2;
UPDATE kaufmlu1.subjectdetails SET anotation = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum. Nunc dapibus tortor vel mi dapibus sollicitudin.', description = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum. Nunc dapibus tortor vel mi dapibus sollicitudin. Integer vulputate sem a nibh rutrum consequat. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Sed convallis magna eu sem. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Nullam sit amet magna in magna gravida vehicula. Nulla', length = 14, lectures = 0, practicals = 2, labs = 2 WHERE id = 3;
UPDATE kaufmlu1.subjectdetails SET anotation = 'Teorie literatury', description = 'Seznámení s historickou literaturou jež je základem moderní společnosti', length = 14, lectures = 2, practicals = 2, labs = 0 WHERE id = 4;
UPDATE kaufmlu1.subjectdetails SET anotation = 'Základy legislativních pojmů a jejich dopady na realitu', description = 'Seznámení s běžným právním řádem, Občanský zákoník, Zákoník práce a další bežná legislativa', length = 14, lectures = 2, practicals = 2, labs = 0 WHERE id = 5;
UPDATE kaufmlu1.subjectdetails SET anotation = 'Nadstavba A02-PR, rozšíření o IT nuanace', description = 'Seznámení s legislativou vázanou na IT', length = 14, lectures = 2, practicals = 0, labs = 0 WHERE id = 6;
UPDATE kaufmlu1.subjectdetails SET anotation = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum.', description = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum. Nunc dapibus tortor vel mi dapibus sollicitudin. Integer vulputate sem a nibh rutrum consequat. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Sed convallis magna eu sem. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Nullam sit amet magna in magna gravida vehicula. Nulla', length = 14, lectures = 2, practicals = 0, labs = 2 WHERE id = 7;
UPDATE kaufmlu1.subjectdetails SET anotation = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum. Nunc dapibus tortor vel mi dapibus sollicitudin.', description = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum. Nunc dapibus tortor vel mi dapibus sollicitudin. Integer vulputate sem a nibh rutrum consequat. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Sed convallis magna eu sem. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim.', length = 20, lectures = 2, practicals = 6, labs = 0 WHERE id = 8;
UPDATE kaufmlu1.subjectdetails SET anotation = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum. Nunc dapibus tortor vel mi dapibus sollicitudin. Integer vulputate sem a', description = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum. Nunc dapibus tortor vel mi dapibus sollicitudin. Integer vulputate sem a nibh rutrum consequat. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Sed convallis magna eu sem. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Nullam sit amet magna in magna gravida vehicula. Nulla', length = 10, lectures = 0, practicals = 0, labs = 0 WHERE id = 9;
UPDATE kaufmlu1.subjectdetails SET anotation = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum. Nunc dapibus tortor vel mi dapibus sollicitudin. Integer vulputate sem a', description = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum. Nunc dapibus tortor vel mi dapibus sollicitudin. Integer vulputate sem a nibh rutrum consequat. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Sed convallis magna eu sem. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Nullam sit amet magna in magna gravida vehicula. Nulla', length = 40, lectures = 4, practicals = 6, labs = 2 WHERE id = 10;
UPDATE kaufmlu1.subjectdetails SET anotation = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum. Nunc dapibus tortor vel mi dapibus sollicitudin. Integer vulputate sem a', description = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum. Nunc dapibus tortor vel mi dapibus sollicitudin. Integer vulputate sem a nibh rutrum consequat. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Sed convallis magna eu sem. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Nullam sit amet magna in magna gravida vehicula. Nulla', length = 14, lectures = 0, practicals = 0, labs = 0 WHERE id = 11;
UPDATE kaufmlu1.subjectdetails SET anotation = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum. Nunc dapibus tortor vel mi dapibus sollicitudin. Integer vulputate sem a', description = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque ipsum. Nunc dapibus tortor vel mi dapibus sollicitudin. Integer vulputate sem a nibh rutrum consequat. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Sed convallis magna eu sem. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Nullam sit amet magna in magna gravida vehicula. Nulla', length = 21, lectures = 0, practicals = 0, labs = 0 WHERE id = 12;
UPDATE kaufmlu1.subjectdetails SET anotation = 'Uvedení do plánování v kontextu rychle se měnícího prostředí.', description = 'Naučíme Vás jak plánovat v prostředí, které se Vám pod rukami mění a zároveň je nutné minimalizovat změny plánu. Podíváme se na dlouhodobější, ale i rychlé taktické plány', length = 14, lectures = 2, practicals = 4, labs = 2 WHERE id = 13;

INSERT INTO classtypes (id, name) VALUES (1, 'Přednáška');
INSERT INTO classtypes (id, name) VALUES (2, 'Cvičení');
INSERT INTO classtypes (id, name) VALUES (3, 'Laboratoře');

INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (1, 1, 1, '11:00:00', 1, 'T2:D3-309', 1);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (2, 1, 2, '14:30:00', 1, 'KN:E-311', 2);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (3, 1, 2, '16:15:00', 1, 'KN:E-311', 2);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (4, 1, 2, '10:30:00', 2, 'KN:E-311', 2);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (5, 1, 2, '16:15:00', 2, 'KN:E-311', 2);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (6, 2, 1, '09:15:00', 4, 'T2:A4-203', 2);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (7, 2, 2, '11:00:00', 4, 'T2:C3-54', 4);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (8, 2, 2, '11:00:00', 4, 'T2:A4-405', 5);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (9, 2, 2, '11:00:00', 4, 'T2:A4-404', 6);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (10, 2, 3, '12:45:00', 4, 'T2:C3-54', 4);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (11, 2, 3, '12:45:00', 4, 'T2:A4-405', 5);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (12, 2, 3, '12:45:00', 4, 'T2:A4-404', 6);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (13, 4, 1, '09:30:00', 1, 'T2:D3-209', 5);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (14, 4, 2, '18:00:00', 3, 'T2:D3-337', 5);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (15, 6, 1, '10:45:00', 1, 'T2:A4-200', 1);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (16, 5, 1, '10:00:00', 4, 'T2:C3-54', 6);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (17, 5, 2, '11:00:00', 2, 'T2:C3-54', 2);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (18, 13, 1, '07:30:00', 1, 'T2:A4-201', 1);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (19, 13, 2, '09:30:00', 1, 'T2:D3-337', 2);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (20, 13, 2, '10:15:00', 1, 'T2:H4-110', 2);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (21, 13, 3, '14:30:00', 4, 'KN:E-311', 6);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (22, 7, 1, '07:30:00', 1, 'KN:E-311', 1);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (23, 7, 3, '11:50:00', 5, 'T2:C3-54', 4);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (24, 3, 3, '11:50:00', 2, 'KN:E-311', 4);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (25, 3, 2, '10:20:00', 1, 'T2:D3-337', 4);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (26, 8, 1, '11:50:00', 3, 'T2:A4-200', 4);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (27, 8, 2, '15:30:00', 2, 'T2:A4-201', 5);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (28, 8, 2, '11:35:00', 3, 'T2:H4-110', 5);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (29, 8, 2, '18:00:00', 4, 'T2:H4-110', 5);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (30, 10, 1, '15:20:00', 1, 'T2:D3-209', 1);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (31, 10, 1, '16:30:00', 2, 'T2:D3-309', 1);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (32, 10, 2, '07:30:00', 1, 'T2:D3-337', 4);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (34, 10, 2, '07:30:00', 1, 'T2:C3-54', 5);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (35, 10, 2, '07:30:00', 5, 'T2:H4-110', 5);
INSERT INTO kaufmlu1.classes (id, subjectId, type, timeOfDay, dayOfWeek, location, teacher) VALUES (36, 10, 3, '07:30:00', 4, 'T2:H4-110', 4);
