name: Deploy to toad
on:
  release:
    types: [published]
jobs:
  SCP-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create deploy folder
        run: |
          mkdir deploy
          cp *.php deploy
      - name: scp-root
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          local: deploy
          remote: /home/kaufmlu1/www/semestralka
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
      - name: scp-css
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          local: css
          remote: /home/kaufmlu1/www/semestralka/css
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
      - name: scp-model
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          local: model
          remote: /home/kaufmlu1/www/semestralka/model
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
      - name: scp-admin
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          local: admin
          remote: /home/kaufmlu1/www/semestralka/admin
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
      - name: scp-assets
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          local: assets
          remote: /home/kaufmlu1/www/semestralka/assets
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
      - name: scp-js
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          local: js
          remote: /home/kaufmlu1/www/semestralka/js
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
      - name: scp-docs
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          local: docs
          remote: /home/kaufmlu1/www/dokumentace
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
